<?php
/**
 * Copyright © MageKey. All rights reserved.
 */

?>
<?php
/**
 * Template for displaying bestsellers widget
 *
 * @var $block \MageKey\BestsellerWidget\Block\Widget
 */
if ($itemsCount = $block->getItemsCount()) {
    $mode = 'grid';

    $image = 'mgk_bestseller_products_widget_grid';
    $title = $block->getTitle();
    $periodLabels = $block->getLabels();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
}
?>

<?php if ($itemsCount): ?>
<div class="block widget block-mgk-bestseller">
    <?php if ($title): ?>
    <div class="block-title">
        <strong role="heading" aria-level="2"><?= $block->escapeHtml($title) ?></strong>
    </div>
    <?php endif; ?>
    <div class="block-content"
         data-mage-init='{
            "tabs": {"openedState":"active"}
         }'>
        <?php if ($itemsCount > 1): ?>
        <div class="tab-links">
            <?php foreach ($block->getPeriods() as $period) : ?>
            <div class="tab-title" data-role="collapsible">
                <a class="tab-link action" data-toggle="switch" href="#bestseller-<?= $period ?>"><?= $periodLabels[$period] ?></a>
            </div>
            <?php endforeach; ?>
        </div>
        <?php endif; ?>
        <?php foreach ($block->getPeriods() as $period) : ?>
            <?php $_items = $block->getItemsCollection($period); ?>
            <?php if ($_items->count()): ?>
            <div class="items period-<?= $period ?>" id="#bestseller-<?= $period ?>" data-role="content">
                <div class="products-<?= /* @escapeNotVerified */ $mode ?> <?= /* @escapeNotVerified */ $mode ?>">
                    <ol class="product-items">
                        <?php $iterator = 1; ?>
                        <?php foreach ($_items as $_item): ?>
                            <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
                            <div class="product-item-info">
                                <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product-item-photo">
                                    <?= $block->getImage($_item, $image)->toHtml() ?>
                                </a>
                                <div class="product-item-details">
                                    <strong class="product-item-name">
                                        <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                           href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>"
                                           class="product-item-link">
                                            <?= $block->escapeHtml($_item->getName()) ?>
                                        </a>
                                    </strong>
                                    <?= /* @escapeNotVerified */ $block->getProductPriceHtml(
                                        $_item,
                                        \Magento\Catalog\Pricing\Price\FinalPrice::PRICE_CODE
                                    ) ?>

                                    <?php if ($templateType): ?>
                                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>

                                    <?php if ($showWishlist || $showCompare || $showCart): ?>
                                        <div class="product-item-actions">
                                            <?php if ($showCart): ?>
                                                <div class="actions-primary">
                                                    <?php if ($_item->isSaleable()): ?>
                                                        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                            <button class="action tocart primary"
                                                                    data-mage-init='{"redirectUrl":{"url":"<?= /* @escapeNotVerified */ $block->getAddToCartUrl($_item) ?>"}}'
                                                                    type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                            </button>
                                                        <?php else: ?>
                                                            <?php
                                                                $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                            ?>
                                                            <button class="action tocart primary"
                                                                    data-post='<?= /* @escapeNotVerified */ $postData ?>'
                                                                    type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                            </button>
                                                        <?php endif; ?>
                                                    <?php else: ?>
                                                        <?php if ($_item->getIsSalable()): ?>
                                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                                        <?php else: ?>
                                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                            <?php if ($showWishlist || $showCompare): ?>
                                                <div class="actions-secondary" data-role="add-to-links">
                                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
                                                        <a href="#"
                                                           data-post='<?= /* @escapeNotVerified */ $block->getAddToWishlistParams($_item) ?>'
                                                           class="action towishlist" data-action="add-to-wishlist"
                                                           title="<?= /* @escapeNotVerified */ __('Add to Wish List') ?>">
                                                            <span><?= /* @escapeNotVerified */ __('Add to Wish List') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                        <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                                        <a href="#" class="action tocompare"
                                                           data-post='<?= /* @escapeNotVerified */ $compareHelper->getPostDataParams($_item) ?>'
                                                           title="<?= /* @escapeNotVerified */ __('Add to Compare') ?>">
                                                            <span><?= /* @escapeNotVerified */ __('Add to Compare') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?= ($iterator == count($_items)+1) ? '</li>' : '' ?>
                        <?php endforeach ?>
                    </ol>
                </div>
            </div>
            <?php endif; ?>
        <?php endforeach ; ?>
    </div>
</div>
<?php endif; ?>
